### ISSUE TITLE
Website -Kunde neuer Request

### ISSUE THREAD

**Issue by TheFoogle** [Glaeydar/Projekt-Car-Sharing-Management#123]
Folgender Request wird noch von der Kundenwebsite benötigt:
Anzeigen der Account Details
{ "request" : "getAccountInfo" }
Anwort sollte dann sein:
FirstName, LastName, DateOfBirth, MemberSince, komplette Anschrift (Street, HouseNo, PLZ, City), Email, Telephone, bei Bankeinzug IBAN und BIC bzw. bei Kreditkarte mit CreditcardnNo und ValidityDate (Gültigkeit), Infos über Kontoinhaber: FirstName, LastName, komplette Anschrift (Street, HouseNo, PLZ, City), AccountStatus (locked/ activated)

**Comment by Glaeydar** [comment]
getCustomerDetail
