### ISSUE TITLE
Benachrichtigung zu einer geplanten Reservierung

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#33]
Wie wird ein Kunde zu seiner geplanten Reservierung benachrichtigt?

Situation:
Der Kunde reserviert um 9 Uhr ein Fahrzeug für 12 Uhr.
Das System führt die Reservierung durch ohne ein Fahrzeug zuzuteilen, dies wird erst später gemacht.
Eine halbe Stunde vor geplantem Fahrtantritt teilt das System dem Kunden mit, an welchem Standort welches Fahrzeug für ihn reserviert ist.

Problem:
Wie kann der Kunde diese Benachrichtigung erhalten?
Die App lädt nur die Website -> Keine kundenspezifische Benachrichtigung möglich
Via Mail -> Telekomkunden haben das Nachsehen, keine mobile Daten (eigene Tendenz)
Via SMS -> (Noch) nicht geplant, muss aktuell dann durch Personal durchgeführt werden
Via Website -> Eintrag in Fahrtenübersicht, Kunde muss nachschauen

**Comment by Franztom** [comment]
Ich hätte es sowohl als Mail gesendet, als auch in der Fahrtenübersicht angezeigt.
