### ISSUE TITLE
Distanzberechnung für die Ermittlung nächstgelegener KFZ

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#36]
Er wird eine Library oder eigene Lösung benötigt zur Ermittlung des nächstgelegenen KFZs benötigt.
Diese muss mit OpenStreetMap kompatibel sein.

**Comment by MachDasLichtAus** [comment]
OSRM zur Ermittlung des nächstgelegenen Fahrzeugs verwenden. 
http://router.project-osrm.org/table/v1/driving/ gefolgt von den koordinaten des referenzpunkts und den Koordinaten aller verfügbarer Fahrzeuge. sämtliche koordinaten werden durch ; getrennt (z.B. 13.388860,52.517037; ) zurückgegeben wird ein JSON mit den Abständen der Fahrzeuge zum Referenzpunkt. Aus diesen Distanzen müssen dann die geringsten gesucht und ausgegeben werden.
