### ISSUE TITLE
Terminologie in den Dokumenten vereinheitlichen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#42]
- [x] UML-Diagramme

- [x] Pflichtenheft

- [x] Lastenheft

- [x] Risikoanalyse

- [x] Mastertestplan

- [x] Glossar

**Comment by Glaeydar** [comment]
Pflichtenheft 
Abb. 15: Neues Auto hinzufügen -> Neues Fahrzeug 
Abb. 16: Auto bearbeiten -> Fahrzeug bearbeiten
Abb. 27: Auto -> Fahrzeug, Google Maps -> OpenStreetMap
Abb. 28: Google Maps -> OpenStreetMap
Abb. 32 - 35, 38: Auto -> Fahrzeug
Abb. 39 - 40: Neues Auto hinzufügen -> Neues Fahrzeug 
Abb. 41 - 42: Auto editieren / Auto bearbeiten -> Fahrzeug bearbeiten
Abb. 51: Autos -> Fahrzeuge
Abb. 53, 56: Auto -> Fahrzeug

@ruakin @Fobsi @TheFoogle @robybeen

**Comment by robybeen** [comment]
erledigt.
