### ISSUE TITLE
UMLs an Datenbank anpassen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#44]
Prüfen, ob alle Aspekte der UMLs auch in der Datenbank abgebildet sind.

**Comment by Franztom** [comment]
- Keine Historie der Karte.
- Welche ist wichtiger? KarteID oder AccID?
- Evt. Kartennummer direkt zum Account schreiben?

**Comment by Glaeydar** [comment]
Info: Spezifikationen angleichen
