### ISSUE TITLE
Risikoanalyse ins Pflichtenheft einfügen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#46]
Welche Maßnahmen werden gegen die einzelnen Risiken unternommen, wie werden diese umgesetzt?

**Comment by Franztom** [comment]
Zum Beispiel: Verschlüsselung soll es geben, wie soll diese in etwa aussehen?

**Comment by Glaeydar** [comment]
zB SHA-512

**Comment by robybeen** [comment]
Erwähnen, dass es eine Kartenverschlüsselung geben wird

**Comment by robybeen** [comment]
> Erwähnen, dass es eine Kartenverschlüsselung geben wird

Done
