### ISSUE TITLE
Abbildungen im Pflichtenheft überarbeiten

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#47]
- [x] Abb. 44: Kunde aktiviert Karte sobald er sie erhält, auf der Verwaltungswebsite muss wegen dem zeitlichen Abgleich besser so etwas stehen wie: Warte auf Kundenaktivierung.

- [x] Abb. 59:  Nochmal durchsprechen. Eigentlich wird ein reserviertes Auto erst bei einer Stornierung oder durch das Ende des Reservierungszeitraums wieder freigegeben.

- [x] Abb. 61: Hier ergeben sich noch Anforderungen an andere Komponenten

**Comment by robybeen** [comment]
Abb. 58 statt 59

**Comment by Glaeydar** [comment]
Bzgl. Abb 61 (Nicht-Reservierbarkeit von Fahrzeugen):

Ein Mitarbeiter eine zeitliche Sperre ein (zB 05.03.2019 - 07.03.2019). Diese wird in der Datenbank gespeichert (ID, Timestamp, Date, Date).
Dazu werden alle in dem Zeitraum liegenden Reservierungen abgesagt und der jeweilige Kunde benachrichtigt. 
Ebenfalls ist die Reservierung nicht möglich.

**Comment by Franztom** [comment]
Bitte ins Pflichtenheft einarbeiten, was Mike oben angemerkt hat.
@Glaeydar @Fobsi  @TheFoogle @truongtuannam

**Comment by Fobsi** [comment]
Erledigt
