### ISSUE TITLE
Traceability- Map erstellen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#48]
Verbindung zwischen Lastenheft und Pflichtenheft.
Lastenheft ist das was und Pflichtenheft das wie. 
Die Traceability-Map stellt die Verbindung her und liefert zu jedem Was das Wie.
-> Soll zeigen, dass nichts übersehen wurde.

**Comment by Franztom** [comment]
Benötigt Besprechung der gelb markierten Felder. Hierzu habe ich noch keine Spezifikation gefunden.

**Comment by Franztom** [comment]
Jeder geht seinen Teil durch, und überprüft für die gelben Felder, ob es eine Spezifikation dafür gibt.

**Comment by robybeen** [comment]
> Jeder geht seinen Teil durch, und überprüft für die gelben Felder, ob es eine Spezifikation dafür gibt.

K&T Done

**Comment by robybeen** [comment]
Notizen in UML, ggf. Mockups/ Storyboards erstellen um die restliche Anforderungen zu tracen

**Comment by robybeen** [comment]
Anpassungen wurden gemacht. T_005 muss diskutiert werden, ansonsten ist bei K&T alles erledigt
