### ISSUE TITLE
Saubere definition des Optimierungs-Algorithmus

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#54]

**Comment by Franztom** [comment]
Ich füge das Dokument noch ins Pflichtenheft ein, Martin kontrolliert es auf Terminologie und Rechtschreibfehler

**Comment by Franztom** [comment]
Dokument ins Pflichtenheft eingefügt

**Comment by MachDasLichtAus** [comment]
done
