### ISSUE TITLE
Anpassen der Anforderungen im Bezug auf fixe Ladestationen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#60]
Datenbank: 

- [x] Attribut AmountOfTank aus der Tabelle ChargeStation kann entfernt werden

- [x] Zusätzliches boolean Attribut "fixed" in der Tabelle ChargeStation muss hinzugefügt werden

WebsiteVerwaltung:

- [x] Abb. 11 im Pflichtenheft braucht Überarbeitung: siehe Protokoll vom 18.03

**Comment by truongtuannam** [comment]
Beide Anforderungen bei der Datenbank wurden erledigt.

**Comment by Fobsi** [comment]
Abbildung wurde überarbeitet.
