### ISSUE TITLE
Analysephase fertigstellen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#62]
Datenbank:
- [x] Tabelle BILLADRESSE: GENDER umbenennen

- [x] Tabelle BUSINESS: Warum braucht man BusinessID?

- [x] Tabelle BUSINESS: Warum braucht man diese Tabelle?

- [x] Tabelle BUSINESS: TerrorFlag sollte in Tabelle Car

- [x] Namen in den Tabellen länger und konkreter machen 

- [x] Tabelle CAR: TUEV sollte eher Date - Typ sein statt Varchar

- [x] Tabelle CAR: Was war mit Appointment gemeint?

- [x] Tabelle NOTIFICATION: Braucht Verbindung zu anderen Tabellen, oder ist sie unnötig?

GUI-Prototyp:
- [x] ABB. 2: Es fehlt das aussteigen des Kunden und das Abschließen des Autos. Es fehlen die 15 Minuten, die das Auto wieder aufgeschlossen werden kann.

- [x] ABB. 10: Negativer Fall der Reservierung fehlt

- [x] Negativ- Fälle müssen weiter ausgeführt werden

Traceability- Map:
- [x] Hinzufügen von Systemtests

Systemtests und Risikoanalyse
- [x] Überprüfen, ob sie noch aktuell sind

Pflichtenheft:
- [x] Fehlermeldungen aktualisieren

Mastertestplan:
- [x] Wer testet was?

**Comment by Franztom** [comment]
Zur Datenbank: Nam hat sich, glaube ich, auch Notizen gemacht. Falls ich was vergessen habe oder falsch aufgeschrieben, bitte verbessern.

**Comment by truongtuannam** [comment]
-Bei der Notifikation Tabelle denke ich in dem Moment braucht er wahrscheinlich keine Verbindung mit anderen Tabelle. Er braucht keine Informationen von anderen Tabellen, oder er abhängig von anderen Informationen von anderen Tabellen. 
-Appointment: Nächste Termin eine Wartung eines Fahrzeuges. Diese Variablennamen wird als NextUpkeepAppointMent umbenennen.

**Comment by robybeen** [comment]
dran denken. TUEV ist ein Verein. Bei Gelegenheit bitte in "Wartungstermin" oder "HU Termin" oder "Hauptuntersuchung" umbennen

**Comment by Franztom** [comment]
Im Lastenheft, WK_009: Um das endgültig festzulegen, kann man so eine neue Ladestation vorschlagen, oder geht es nur, indem man bei der Reservierung einen POI auswählt, an dem noch keine Ladestation steht, und das wird dann als Vorschlag gewertet?

**Comment by Franztom** [comment]
Systemtest auf Aktualität überprüft

**Comment by truongtuannam** [comment]
Fragen:
Wie soll man "GENDER" umbenennen?

Warum braucht man die Tabelle "Business"?

Wie kann man unterscheidet zwischen Privat Nutzer und andere?

TerrorFlag sollte in Tabelle Car?

Welcher Variablenname sollte geändert werden?

Welche Datentyp für TUEV? Und braucht er neue Name?

**Comment by robybeen** [comment]
ich mache das "wer testet was" im Mastertestplan

und

Systemtests und Risikoanalyse:, ob sie noch aktuell sind

**Comment by Glaeydar** [comment]
> Fragen:
> Wie soll man "GENDER" umbenennen?
"salutation" vielleicht

> Warum braucht man die Tabelle "Business"?
Ursprünglich wollten wir dort allgemeine Geschäftsdaten speichern.

> Wie kann man unterscheidet zwischen Privat Nutzer und andere?
Gar nicht, gewerbliche Fahrten sind nicht vorgesehen.

> TerrorFlag sollte in Tabelle Car?
Macht für mich keinen Sinn. Hat nichts mit Fahrzeugen zu tun.
  
> Welcher Variablenname sollte geändert werden?
  
> Welche Datentyp für TUEV? Und braucht er neue Name?
"maintenance"

**Comment by Glaeydar** [comment]
> * Fehlermeldungen aktualisieren

Was genau ist damit gemeint?

**Comment by Franztom** [comment]
> 
> 
> > * Fehlermeldungen aktualisieren
> 
> Was genau ist damit gemeint?

Das mache ich. Das sind die Fehlermeldungen unten im Pflichtenheft.

**Comment by Franztom** [comment]
> 
> Systemtests und Risikoanalyse:, ob sie noch aktuell sind

Systemtests sind schon geprüft

**Comment by truongtuannam** [comment]
> > Warum braucht man die Tabelle "Business"?
> > Ursprünglich wollten wir dort allgemeine Geschäftsdaten speichern.
So Business ist über "unsere Geschäft"(ECS), nicht von Kunden?


 > > TerrorFlag sollte in Tabelle Car?
> > Macht für mich keinen Sinn. Hat nichts mit Fahrzeugen zu tun.
In der Meeting mit Herr Nikolaropoulos haben wir gesprochen, dass wenn Terror gibt(Krieg, Earthquake...), wurden allen Fahrzeug geblockt (nicht nutzbar). Mit der TerrorFlag in dem Fahrzeug Tabelle setzen, so dass, wenn jemand versucht, das Auto zu benutzen, diese blockiert wird.
Aber hatten wir nicht gewusst, was genau das Business damals bedeutet. TerrorFlag bleibt in Business.

**Comment by robybeen** [comment]
"wer testet was" im Mastertestplan done

still to do: Risikoanalyse auf Aktualität prüfen

**Comment by robybeen** [comment]
Die Risiken die mit 9 versehen sind sollten auf keinen Fall "hoch" als Wahrscheinlichkeit haben, wir sind keine Amateure. Die Auswirkung sollte auch nicht "hoch" sein weil man dadurch nur im Zeitverzug ist und keine tragische Folgen deswegen entstehen.

Risikostufen sind zum Teil merkwürdig.

ein paar Beispiele:

"Erfolgreiches Login mit falschen Daten" Risiko 6 und
"Website nicht aufrufbar" ebenfalls Risiko 6.

"App stürzt ab/ funktioniert nicht" Risko 6 und
"Mit gefälschter Karte das Fahrzeug öffnen" Risiko 6.

"Datenbankverwalteraccount ohne Passwort" Risiko 2 während
"Doppelbuchungen von Fahrzeugen" Risiko 9.

und es lassen bestimmt noch mehrere finden.

**Comment by robybeen** [comment]
Risikoanalyse: 

aktuell ---- ??? Braucht Erweiterung wegen den neu gekommenen Anforderungen.
Überarbeitung der bisherigen Risiken ?? Wahrscheinlich schon. ( vielleicht wird dafür ein neues Issue erstellt ( ich könnte mich um diesen neuen Issue kümmern wenn es dazu kommt.)

Meine Teile aus #62 sind somit erledigt.

**Comment by Glaeydar** [comment]
> "Erfolgreiches Login mit falschen Daten" 
Erhöhtes Risiko, Datenschutz & Deutschland wird teuer

> "Website nicht aufrufbar" ebenfalls Risiko 6.
Es kommt kein Geld rein, wäre aber eher Netzadministration

> "Mit gefälschter Karte das Fahrzeug öffnen" Risiko 6.
s. Login mit f. Daten

> "Datenbankverwalteraccount ohne Passwort" 
Totale Katastrophe
