### ISSUE TITLE
E2E- Mockup

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#63]
Vorüberlegungen müssen angestellt werden. Man braucht eine Datenbank, eine Website, eine Serverapplikation, ein Tablet. Wie soll es zusammen spielen? Was soll hin und her geschickt werden?

Beispiel von der Vorgruppe:
Man registriert sich auf der Website. Man erkennt, das in der Datenbank der registrierte Kunde auftaucht. Wenn man händisch eine SQL injektion eingibt, soll sich der angelegte Kunde auf der Website anmelden können.

**Comment by Franztom** [comment]
Bis zum 28.03.19 sollen nur die Vorüberlegungen fertig sein.

**Comment by Glaeydar** [comment]
Nutzer registriert sich auf der Website -> Daten an Server  -> Daten in DB speichern
Nutzer reserviert über App -> Daten an Server  -> Daten in DB speichern
Nutzer schaut dich die Reservierung auf dem Desktop an -> Anfrage Übersicht Reservierungen an Server ->  Auslesen aus DB -> Rückantwort
Nutzer will das Fahrzeug freischalten ->Anfrage an Server ->  Auslesen aus DB -> Rückantwort

**Comment by robybeen** [comment]
Kleiner Prototyp für das Tablet mit 3 Buttons, ein Textfeld wurde erstellt. Morgen Abend implementiere ich saubere Aktionen für die Events. Zum Teil will man nicht, dass sich die ganze Anwendung aufhängt wenn die Verbindung nicht hergestellt werden kann usw. Außerdem, es wäre elegant jetzt schon sich Klassen und so zu schreiben, wird aber wegen Zeitdruck zuerst nicht möglich sein.

**Comment by robybeen** [comment]
Software hochgeladen. Sollte serverseitig getestet werden.

**Comment by Franztom** [comment]
E2E-Mockup muss noch ausführlich getestet werden.
