### ISSUE TITLE
Komponentendiagramme erstellen

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#66]
- [ ] Server Application
- [ ] Mobile App
- [ ] Website Kunde
- [x] Website Verwaltung
- [x] Tablet
- [x] Kartenleser
- [ ] Algorithmen

**Comment by robybeen** [comment]
Ihr könnt eure Diagramme einzeln hier hochladen:
https://drive.google.com/drive/folders/1N5zbLsiNGDQJeddA7qC06FtdgGQW5gJW

Tablet und CardReader done

**Comment by Franztom** [comment]
Wird hintenangestellt und später bearbeitet, eventuell Feindesign
