### ISSUE TITLE
Integrationstests erstellen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#67]
E2E - Mockup ist laut Nikolaropoulos schon ein Integrationstest. 
Wir benötigen noch weitere und man muss ein Dokument für sie erstellen.

**Comment by robybeen** [comment]
Link zum hochladen:
https://drive.google.com/open?id=1c7HP7Bb3YBWmocyDq9aLMvRG9zeHGVat

**Comment by Franztom** [comment]
Ersterstellung des Dokuments Systemtests_Gesammt_ECMS fertig.
HIer können nach und nach die einzelnen Systemtests eingefügt werden.

**Comment by robybeen** [comment]
CardReader-Tablet, Tablet-Server should be done.
Vielleicht sollte man etwas Anforderungen noch im Pflichtenheft/ Lastenheft nachpflegen, Muss besprochen werden.

**Comment by Franztom** [comment]
Benötigt neue Abklärung mit Herrn Nikolaropoulos
