### ISSUE TITLE
Schnittstellendefinition

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#68]
Feinere Definition der Schnittstellen zwischen den einzelnen Komponenten.

**Comment by robybeen** [comment]
Tablet+ Server sollte soweit stehen.
Tablet+ Kartenlesegerät ist im Endeffekt USB Übertragung. Wie die Datenpakete aussehen sollen ist noch unklar, wird aber wahrscheinlich nicht drigend gebraucht.

**Comment by Glaeydar** [comment]
Sollte jedoch auch irgendwo definiert sein, damit es niedergeschrieben ist.

**Comment by Franztom** [comment]
Ich habe die Schnittstellen mal durchgesehen.
Folgende Fragen sind entstanden:
- Braucht die App extra Schnittstellendefinitionen, wenn ja, wo stehen sie geschrieben?
- Braucht man extra Schnittstellendefinitionen für das Kartenlesegerät?
- Fehlt noch die Schnittstellendefinition der Server Applikation?

**Comment by Franztom** [comment]
Nach der Schnittstellendefinition sind Klassendiagramme dran, um festzulegen, welche Klasse welche Methoden mit welchen Namen und welchen Parametern bereitstellt.

**Comment by Franztom** [comment]
Schnittstellendefinition des KArtenlesegeräts fehlt noch.
Nächstegelegenes Auto finden fehlt noch -> Florian kümmert sich drum.
Server benötigt keine, da alle anderen drum herum die Schnittstellen definieren.
Datenbank benötigt keine, da er nur SQL Anfragen bekommt.

**Comment by robybeen** [comment]
Kartenlesegerät done. Eine Tabelle mit den ganzen möglichen Nachrichtenarten erfolgt in Feindesign.

**Comment by robybeen** [comment]
Die Tabelle: https://drive.google.com/open?id=1lNBrxFn2o5057d9M8KhXoBCgj_0kuOdp
