### ISSUE TITLE
Klassendiagramme erstellen

### ISSUE THREAD

**Issue by Franztom** [Glaeydar/Projekt-Car-Sharing-Management#70]
Klassendiagramme müssen für die einzelnen Komponentene erstellt werden.

**Comment by robybeen** [comment]
Tablet+ CardReader done

**Comment by ruakin** [comment]
Klassendiagramm der App hochgeladen.

**Comment by MachDasLichtAus** [comment]
Algo Optimierung und Statistik sollte soweit passen, dorer ist bisher nur der automatisch erstellte

**Comment by robybeen** [comment]
Die aktuellste Version: https://drive.google.com/open?id=1mq_HmQCoc2PJIqT20cI02LoIP8_s8o-e
