### ISSUE TITLE
PHP sendet keine Nachricht sobald es auf eine Antwort wartet

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#78]
**Beschreibung des Fehlers**
Sobald das PHP Skript auf eine Antwort seitens des Servers wartet, empfängt der Server keine Nachricht mehr. Wenn das Skript auf keine Antwort wartet wird die Nachricht auch empfangen.

**Schritte um den Fehler zu Reproduzieren**
1. Kommentiere aus
`while ($out = socket_read($socket, 2048, PHP_NORMAL_READ )) {
    echo "Anwort $out .";
}`
2. Fehler tritt auf

**Erwartetes Verhalten**
Erwartet ist, dass das Skript die Nachricht versendet und die Antwort ließt.

**Comment by Fobsi** [comment]
Fehler war die fehlende string Terminierung. Es wurde eine Klasse für die Socket-Aufrufe erstellt und das Skript angepasst.
