### ISSUE TITLE
Reservierungen via SMS über eigene Android App

### ISSUE THREAD

**Issue by Glaeydar** [Glaeydar/Projekt-Car-Sharing-Management#9]
Da es auch möglich sein soll, Reservierungen über eine SMS zu machen, wurde beschlossen dafür eine Android App zu erstellen. Dafür muss das Pflichtenheft, Risikoanalyse & Gantt Chart aktualisiert werden.

Dazu muss jemand sich Gedanken machen über das Bestellungsformat à la:
Von: <Ort> Ab: <Uhrzeit> Dauer: <Dauer>

**Comment by ruakin** [comment]
2. SMS wird an einen Mitarbeiter gesendedet, welcher die Reservierung manuell über die Website einträgt.

**Comment by Glaeydar** [comment]
SMS wird von einem Mitarbeiter empfangen, welcher die Reservierung eigenhändig anlegt.
